FROM php:fpm

RUN apt-get update && apt-get install -y \
      libicu-dev \
      libpng-dev \
      libfreetype6-dev \
      libjpeg62-turbo-dev \
      libpq-dev \
      libmcrypt-dev \
      gcc \
      make \
      autoconf \
      libc-dev \
      pkg-config \
    && rm -r /var/lib/apt/lists/* \
    && pecl install mcrypt-1.0.1 \
    && docker-php-ext-enable mcrypt \
    && echo extension=/usr/local/lib/php/extensions/no-debug-non-zts-20170718/mcrypt.so > /usr/local/etc/php/mcrypt.ini \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install \
      intl \
      mysqli \
      mbstring \
      gd \
      pcntl \
      pdo_mysql \
      pdo_pgsql \
      pgsql \
      zip \
      opcache