{
    "version": "3",
    "volumes": {
        "postgres_data": {},
        "mysql_data": {}
    },
    "services": {
        "postgres": {
            "image": "postgres",
            "restart": "always",
            "volumes": [
                "postgres_data:/var/lib/postgresql/data/",
                "./init:/docker-entrypoint-initdb.d"
            ],
            environment: {
                POSTGRES_USER: "douser",
                POSTGRES_PASSWORD: "douser",
                POSTGRES_DB: "douser"
            },
            "ports": [
                "5432:5432"
            ],
        },
        "php": {
            "build": {
                "context": "./",
                "dockerfile": "Dockerfile-php-fpm"
            },
            "volumes": [
                "~/projects:/var/www/"
            ],
            "depends_on": [
                "postgres"
            ]
        },
        "apache": {
            build: "apache",
            restart: "always",
            "volumes": [
                "~/projects:/var/www/",
            ],
            "ports": [
                "80:80"
            ],
            "depends_on": [
                "php"
            ]
        }
    }
}